apiVersion: v1
kind: Secret
metadata:
  name: talana-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://talana_user:talana_password@postgresql-service:5432/talana_production
  RAILS_SECRET_KEY_BASE: 48f08572b5294820614fcaa64b3763ea
