apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-sidekiq
  template:
    metadata:
      labels:
        app: backend-sidekiq
    spec:
      containers:
        - name: sidekiq
          image: ghcr.io/nosenadayo/challenge_talana:latest
          command: ["bundle", "exec", "sidekiq"]
          env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
            - name: REDIS_URL
              value: redis://redis-service:6379/1
