apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      initContainers:
        - name: init-db
          image: ghcr.io/nosenadayo/challenge_talana:latest
          command: ["bundle", "exec", "rails", "db:create", "db:migrate", "db:seed"]
          env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: talana-secrets
                  key: DATABASE_URL
            - name: RAILS_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: talana-secrets
                  key: RAILS_SECRET_KEY_BASE
      containers:
        - name: web
          image: ghcr.io/nosenadayo/challenge_talana:latest
          command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: talana-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              value: redis://redis-service:6379/1
            - name: FRONTEND_URL
              value: http://frontend-service
            - name: RAILS_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: talana-secrets
                  key: RAILS_SECRET_KEY_BASE
