apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-web
  template:
    metadata:
      labels:
        app: backend-web
    spec:
      containers:
        - name: web
          image: ghcr.io/nosenadayo/challenge_talana:latest
          command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
            - name: REDIS_URL
              value: redis://redis-service:6379/1
            - name: FRONTEND_URL
              value: http://frontend-service
