{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1",
    "description": "Documentación de la API"
  },
  "paths": {
    "/api/v1/skills": {
      "get": {
        "summary": "Lista todas las habilidades",
        "tags": [
          "Skills"
        ],
        "responses": {
          "200": {
            "description": "lista de habilidades encontrada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/skill"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ],
  "components": {
    "schemas": {
      "skill": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name"
        ]
      }
    }
  }
}